# Site settings
title: DataFormation
header-img: img/home-bg.jpg
email: support@dataformation.io 
copyright_name: DataFormation
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "https://blog.dataformation.io/"
twitter_username: DataFormationIO 
github_username:  dataformation
# facebook_username:  StartBootstrap
email_username: support@dataformation.io 

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-106039782-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]


redcarpet:
  extensions: ["smart"]